name: Mirror to Gitlab Repo

on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:Katheesh/HNDIT.git'
          destination-repo: 'git@gitlab.com:katheesh/hndit.git'
